### PR TITLE
Change to suit dast-owasp-zap

### PR DESCRIPTION
**Pull request by binarymist**
Add sutUrl to envelopeSchema.
Add lineitem location alternative.
Add metadataSchemaDAST for dast.

@streichsbaer do you have any spare engine outputs you can throw at this to verify I haven't broken anything?

Validates dast-owasp-zap fine now.

### CODE REVIEW

**Review by guardrails-test — COMMENTED** [review]
LGTM, I'll run some more tests later today on other outputs

**Comment by binarymist** [comment]
Was there a reason this never got merged @streichsbaer ?

**Comment by streichsbaer** [comment]
> Was there a reason this never got merged @streichsbaer ?

Yes, because we haven't deployed the DAST engine to production and as a result forgot to merge this.

**Review by streichsbaer — APPROVED** [review]
LGTM

**Pull request merged**
